### ISSUE TITLE
verify_all does not reset index when called from two different tests. 

### ISSUE THREAD

**Issue by aaltat** [approvals/ApprovalTests.Python#32] opened 2018-08-17 07:37 UTC
When I have this pseudo code: 
```
import unittest

from approvaltests.approvals import verify_all
from approvaltests.reporters.generic_diff_reporter_factory import GenericDiffReporterFactory


class GettingStartedTest(unittest.TestCase):
    def setUp(self):
        self.reporter = GenericDiffReporterFactory().get_first_working()

    def test_1(self):
        verify_all('test1', ['1', '2' '3'], self.reporter)
		
    def test_2(self):
        verify_all('test2', ['1', '2' '3'], self.reporter)
```
Then it output for test_1 looks like this: 
```
test1

0) 1
1) 2
2) 3
```
And the test_2 looks like this:
```
test2

3) 1
4) 2
5) 3
```
But I did expect test_2  to look like this: 
```
test2

0) 1
1) 2
2) 3
```
I did expect the index numbering to restart. 

By reading the code, I think the bug is in [list_utils FormatLineItem](https://github.com/approvals/ApprovalTests.Python/blob/master/approvaltests/list_utils.py#L11), because the `index` is not reset. I think problem could be fixed by changing this: 
```
def format_list(alist, formatter, header):
    if formatter is None:
        formatter = FormatLineItem().print_item
    text = header + '\n\n'
    for i in alist:
        text += formatter(i) + '\n'
    return text
```
to his: 
```
def format_list(alist, formatter, header):
    if formatter is None:
        FormatLineItem().index = 0
        formatter = FormatLineItem().print_item
    text = header + '\n\n'
    for i in alist:
        text += formatter(i) + '\n'
    return text
```

**Comment by tdpreece** [comment] 2018-08-18 12:28
Thanks for raising this.  Yes, I would expect the behaviour that you describe above too (i.e. for the numbering to start again from zero for test 2).

This is caused by having  `index` as a class attribute with `print_item` as a `classmethod`:

```python
# approvaltests/list_utils.py
class FormatLineItem(object):
    index = 0

    @classmethod
    def print_item(cls, x):
        text = str(cls.index) + ') ' + str(x)
        cls.index += 1
        return text
```
I think the bug could be fixed by using a standard method on the class instance along with `index` as an attribute on the instance, e.g.

```python
class FormatLineItem(object):
    def __init__(self):
        self.index = 0

    def print_item(self, x):
        text = str(self.index) + ') ' + str(x)
        self.index += 1
        return text
```

What do you think?

**Comment by aaltat** [comment] 2018-08-18 13:05
It's a possible solution. I can try it out and if it works, I can send a PR.

**Comment by aaltat** [comment] 2018-08-21 18:55
@tdpreece solution was the best that I could think of. #33 provides a fix for the problem.

**Closed** 2018-08-22 07:01 UTC
